#!/bin/bash

if [[ $1 == "--help" || -z $1 ]]; then
    echo "Usage: gc \"Commit message\""
    exit 1
fi

git commit -S -m "$1"
if [[ $? -ne 0 ]]; then
    echo "Error: git commit failed."
    exit 1
fi

