#!/bin/bash

if [[ $1 == "--help" ]]; then
    echo "Usage: gdiff [file]"
    echo "Shows changes between commits, commit and working tree."
    exit 0
fi

git diff "$@"
if [[ $? -ne 0 ]]; then
    echo "Error: git diff failed."
    exit 1
fi

