#!/bin/bash

if [[ $1 == "--help" ]]; then
    echo "Usage: gfetch"
    echo "Fetches from the remote repository."
    exit 0
fi

git fetch
if [[ $? -ne 0 ]]; then
    echo "Error: git fetch failed."
    exit 1
fi

