#!/bin/bash

if [[ $1 == "--help" ]]; then
    echo "Usage: gp"
    echo "Runs git push origin main"
    exit 0
fi

git push origin main
if [[ $? -ne 0 ]]; then
    echo "Error: git push failed."
    exit 1
fi

