#!/bin/bash

if [[ $1 == "--help" ]]; then
    echo "Usage: gstatus"
    echo "Shows the working tree status."
    exit 0
fi

git status
if [[ $? -ne 0 ]]; then
    echo "Error: git status failed."
    exit 1
fi

